model_name: VQVAE
data_params:
  dataset: CIFAR10
  batch_size: 128
model_params:
  num_embeddings: 128
  embedding_dim: 32
  hidden_dims : [128, 256]
  n_residual_layers: 2
trainer_params:
  max_epochs: 100