model_name: VQVAE
data_params:
  dataset: CIFAR10
  batch_size: 128
model_params:
  num_embeddings: 256
  embedding_dim: 64
  hidden_dims : [128, 256]
  n_residual_layers: 4
trainer_params:
  max_epochs: 100