model_name: VQVAE
data_params:
  dataset: MNIST
  batch_size: 128
model_params:
  num_embeddings: 128
  embedding_dim: 16
  hidden_dims : [32, 64]
  n_residual_layers: 0
trainer_params:
  max_epochs: 50