model_name: SCVQVAE2D
data_params:
  dataset: CIFAR10
  batch_size: 128
  count_sampling: EXACT
  pixel_sampling: EXACT
model_params:
  num_embeddings: 256
  embedding_dim: 64
  hidden_dims : [128, 256]
  n_residual_layers: 4
trainer_params:
  max_epochs: 50