model_name: SCVQVAE2D
data_params:
  dataset: MNIST
  batch_size: 128
  count_sampling: EXACT
  pixel_sampling: EXACT
model_params:
  num_embeddings: 128
  embedding_dim: 16
  hidden_dims : [32, 64]
  n_residual_layers: 0
trainer_params:
  max_epochs: 100